### ISSUE TITLE
a problem with cmake

### ISSUE THREAD

**Issue by Doinbo** [irobot-ros/ros2-performance#83]
i am so sry to get another problem like that.

![git](https://user-images.githubusercontent.com/95084764/151727736-478d7dec-2ff4-4d67-b72b-a661444362ab.png)

**Comment by alsora** [comment]
This problem is unrelated to this repository.
The error indicates that CMake can't find the `ament_cmake` dependency, which is one of the ROS libraries.

Make sure that ROS is installed on your machine and that you have sourced the corresponding setup file
(e.g. `source /opt/ros/galactic/setup.sh` if this is where you installed ROS)

**Comment by Doinbo** [comment]
will that work when i have built the ros2 here https://docs.ros.org/en/foxy/Installation.html and install the debian ros2 and then  i  make this experiment.

**Comment by alsora** [comment]
Regardless of how you built/installed ROS, you will always have to source the appropriate setup.sh file as I mentioned in my previous message.
This does not apply to this repository but it's a prerequisite for building any ROS package.

If you are using foxy and installed using debians, the instruction should be
```
source /opt/ros/foxy/setup.sh 
```
