### ISSUE TITLE
How to set KeepAll History QoS in JSON files

### ISSUE THREAD

**Issue by Doinbo** [irobot-ros/ros2-performance#89]
may i change the QoS setting here in the json
i do not know if that function
<img width="830" alt="git" src="https://user-images.githubusercontent.com/95084764/152681521-71778b16-9894-4810-9ce2-7c6e05613d45.png">

**Comment by alsora** [comment]
Yes you can change whatever you want. The JSON files in the repository are just examples.

Have you tried to do it?
What makes you think that it wouldn't be possible?

**Comment by Doinbo** [comment]
when i change the qos_history from keep last to keep all
then there is a problem with
( :  intraprocess communication allowed only with keep last history qos policy)

**Comment by alsora** [comment]
This problem is unrelated to the tests.
The error comes from the ROS 2 libraries and it's pretty self-explanatory.

If you want to use "keep all" you should also disable intra-process optimization.

IPC optimization is controlled through the command line options when you start the application.
See https://github.com/irobot-ros/ros2-performance/tree/master/irobot_benchmark#running
You can change `--ipc on` into `--ipc off`
