### ISSUE TITLE
The command provided to run.sh does not exists

### ISSUE THREAD

**Issue by calvinyy-oss** [irobot-ros/ros2-performance#94]
when I try to  "bash scripts/pub_sub_separate_process.sh",it shows that The command provided to run.sh does not exists!!
/home/calvin/performance01_ws/performance_test_factory/lib/performance_test_factory/subscriber_nodes_main.

**Comment by alsora** [comment]
Can you show all the steps that you are doing and the complete terminal output?

**Comment by alsora** [comment]
I fixed a bug that was the cause of your error: https://github.com/irobot-ros/ros2-performance/commit/1901a2f0b50b905ca2faad825a0133856631b37b

You should be able to update your local repository to the latest version to get the fix.

Note that everything under the `scripts` directory is more than 2 years old and not tested/used since then.
It is not recommended to use those scripts

**Comment by calvinyy-oss** [comment]
Thank you！But When I use the benchmark to see the performance ,it is quite different from script file's result like this.I want see the performance of ros2 when there is a pub/sub ,sending different size msgs to see it cpu latency memory etc.
![图片](https://user-images.githubusercontent.com/75769276/161617897-0d5c82e4-83ec-4669-8655-d1b924488caf.png)

**Comment by alsora** [comment]
What the scripts do is just to run executables multiple times and then plot the data.
You can use them, but I don't guarantee that they work.
